export {default as useScreenWidth} from '../hooks/useScreenWidth'
export {default as useAddPageTitle} from '../hooks/useAddPageTitle'
export {default as useAddClassBody} from '../hooks/useAddClassBody'

export {default as UseLoginHook} from '../hooks/authentication/useLogin'
export {default as useLogoutHook} from '../hooks/authentication/useLogout'
export {default as UseRegisterHook} from '../hooks/authentication/useRegister'
export {default as useForgotPassHook} from '../hooks/authentication/useForgotPass'
export {default as useResetPassHook} from '../hooks/authentication/useResetPass'
export {default as useUpdateProfile} from '../hooks/authentication/useUpdateProfile'
export {default as useUpdatePass} from '../hooks/authentication/useUpdatePass'

export {default as useCreateCategory} from '../hooks/categories/useCreateCategories'
export {default as useRetrieveCategories} from '../hooks/categories/useRetrieveCategories'
export {default as useUpdateCategory} from '../hooks/categories/useUpdateCategories'
export {default as useDeleteCategory} from '../hooks/categories/useDeleteCategories'

export {default as useCreateProducts} from '../hooks/products/useCreateProducts'
export {default as useRetrieveProducts} from '../hooks/products/useRetrieveProducts'
export {default as useUpdateProducts} from '../hooks/products/useUpdateProducts'
export {default as useDeleteProducts} from '../hooks/products/useDeleteProducts'

export {default as useCreateProductVariants} from '../hooks/product_variants/useCreateProductVariants'
export {default as useRetrieveProductVariants} from '../hooks/product_variants/useRetrieveProductVariants'
export {default as useUpdateProductVariants} from '../hooks/product_variants/useUpdateProductVariants'
export {default as useDeleteProductVariants} from '../hooks/product_variants/useDeleteProductVariants'

export {default as useRetrieveOrders} from '../hooks/orders/useRetrieveOrders'
export {default as useUpdateOrders} from '../hooks/orders/useUpdateOrders'
export {default as useEnlistProducts} from '../hooks/orders/useEnlistProducts'
export {default as useViewProducts} from '../hooks/orders/useViewProducts'
export {default as useEnlistCart} from '../hooks/orders/useEnlistCart'